service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  iam:
    role: arn:aws:iam::295974408458:role/S3LambdaFullAccess
  environment:
    ACCOUNT_ID: ${aws:accountId}
    REGION: ${aws:region}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  patterns:
    - '!**/*.test.*'

functions:
  importProductsFile:
    handler: ./src/handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
  importFileParser:
      handler: ./src/handler.importFileParser
      role: arn:aws:iam::295974408458:role/LambdaSQSDynamoDBFUllAccess
      events:
        - s3:
            bucket: uploaded-aws-shop
            event: s3:ObjectCreated:*
            rules:
              - prefix: uploaded/
            existing: true
