service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    ACCOUNT_ID: ${aws:accountId}
    REGION: ${aws:region}
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionArn: arn:aws:lambda:eu-west-1:295974408458:function:authorization-service-dev-basicAuthorization

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  patterns:
    - '!**/*.test.*'

functions:
  importProductsFile:
    handler: ./src/handler.importProductsFile
    role: arn:aws:iam::295974408458:role/DynamoDBLambdaAccessRole
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: customAuthorizer

  importFileParser:
      handler: ./src/handler.importFileParser
      role: arn:aws:iam::295974408458:role/LambdaSQSDynamoDBFUllAccess
      events:
        - s3:
            bucket: uploaded-aws-shop
            event: s3:ObjectCreated:*
            rules:
              - prefix: uploaded/
            existing: true
